name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - name: Clone KermanX/slidev
        run: git clone https://github.com/KermanX/slidev
        working-directory: ../
      - name: Install KermanX/slidev
        run: pnpm i
        working-directory: ../slidev
      - name: Build KermanX/slidev
        run: pnpm build
        working-directory: ../slidev
      - name: Install modified version of Slidev
        run: |
          pnpm i ../slidev/packages/parser
          pnpm i -D ../slidev/packages/types
      - name: Run tests
        run: pnpm test
